In [173]:
import numpy as np

In [174]:
import math

### Helper function defenitions

In [175]:
def sigmoid(X):
    shape = X.shape
    ones =  np.ones(shape, dtype=float)
    temp = ones/(ones + np.exp(-X))
    return temp

In [176]:


def sigmoid_1(x):
  return 1 / (1 + math.exp(-x))

In [177]:
def derivatives_sigmoid(Z):
    shape = Z.shape
    ones  = np.ones(shape, dtype=float)
    sigm  = sigmoid(Z)
    one_m_sigm = ones - sigmoid(Z)
    
    temp = np.multiply(sigm , one_m_sigm )
    
    
    return temp

In [178]:
#for debugging
'''
def derivatives_sigmoid(Z):
    shape = Z.shape
    ones  = np.ones(shape, dtype=float)
    sigm  = Z
    one_m_sigm = ones - Z
    
    temp = np.multiply(sigm , one_m_sigm )
    
    
    return temp
'''

'\ndef derivatives_sigmoid(Z):\n    shape = Z.shape\n    ones  = np.ones(shape, dtype=float)\n    sigm  = Z\n    one_m_sigm = ones - Z\n    \n    temp = np.multiply(sigm , one_m_sigm )\n    \n    \n    return temp\n'

### Define Global parameters

In [179]:
lr = 1.0
learning_rate = 0.1

### Create input and output

In [180]:
X = [1, 0 , 1, 0,  1, 0 , 1, 1,  0, 1 , 0, 1]
Y = [1, 1, 0]

In [181]:
X = np.array(X, dtype=float)
Y = np.array(Y, dtype=float)

In [182]:

X = X.reshape(3, 4)
Y = Y.reshape(3, 1)

In [183]:
X, Y

(array([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]]), array([[1.],
        [1.],
        [0.]]))

In [184]:
X.shape, Y.shape

((3, 4), (3, 1))

### Randomly intialize the weights and biases

In [185]:
wh = np.random.random((4,3))
bh = np.random.random((1,3))



In [186]:
#for debugging
'''
wh = [0.42, 0.88 , 0.55, 0.10,  0.73, 0.68 , 0.60, 0.18,  0.47, 0.92 , 0.11, 0.52]
bh = [0.46, 0.72, 0.08]
wh = np.array(wh, dtype=float)
bh = np.array(bh, dtype=float)
wh = wh.reshape(4, 3)
bh = bh.reshape(1, 3)
'''

'\nwh = [0.42, 0.88 , 0.55, 0.10,  0.73, 0.68 , 0.60, 0.18,  0.47, 0.92 , 0.11, 0.52]\nbh = [0.46, 0.72, 0.08]\nwh = np.array(wh, dtype=float)\nbh = np.array(bh, dtype=float)\nwh = wh.reshape(4, 3)\nbh = bh.reshape(1, 3)\n'

In [187]:
wout = np.random.random((3,1))
bout = np.random.random((1,1))

In [188]:
#for debugging
'''
wout = [0.30, 0.25, 0.23]
bout = [0.69]
wout = np.array(wout, dtype=float)
bout = np.array(bout, dtype=float)
wout = wout.reshape(3, 1)
bout = bout.reshape(1, 1)
'''

'\nwout = [0.30, 0.25, 0.23]\nbout = [0.69]\nwout = np.array(wout, dtype=float)\nbout = np.array(bout, dtype=float)\nwout = wout.reshape(3, 1)\nbout = bout.reshape(1, 1)\n'

In [189]:
wh, bh, wout, bout

(array([[0.81713012, 0.08637283, 0.86273144],
        [0.74001592, 0.8800434 , 0.65110095],
        [0.42822768, 0.69629792, 0.28597781],
        [0.12328904, 0.12136981, 0.81218701]]),
 array([[0.73873755, 0.0386873 , 0.00608855]]),
 array([[0.44858273],
        [0.45362512],
        [0.92406105]]),
 array([[0.74673824]]))

In [190]:
wh.shape, bh.shape, wout.shape, bout.shape

((4, 3), (1, 3), (3, 1), (1, 1))

### Forward propagation

In [191]:
hidden_layer_input = np.matmul(X, wh) + bh 

In [192]:
hiddenlayer_activations = sigmoid(hidden_layer_input)

In [193]:
hidden_layer_input, hiddenlayer_activations

(array([[1.98409536, 0.82135805, 1.1547978 ],
        [2.1073844 , 0.94272785, 1.96698481],
        [1.60204252, 1.04010051, 1.46937651]]),
 array([[0.87911705, 0.69452454, 0.76038616],
        [0.89161883, 0.71965034, 0.87728688],
        [0.83230366, 0.7388694 , 0.8129626 ]]))

In [194]:
output_layer_input = np.matmul(hiddenlayer_activations, wout) + bout

In [195]:
output = sigmoid(output_layer_input)

In [196]:
output_layer_input, output

(array([[2.15879198],
        [2.28382116],
        [2.20649208]]), array([[0.8964875 ],
        [0.90752822],
        [0.90083099]]))

In [197]:
E = Y - output

In [198]:
E

array([[ 0.1035125 ],
       [ 0.09247178],
       [-0.90083099]])

### Back propagation

In [199]:
slope_output_layer = derivatives_sigmoid(output)

In [200]:
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)

In [201]:
slope_output_layer, slope_hidden_layer

(array([[0.20580455],
        [0.20484626],
        [0.20542824]]), array([[0.20730023, 0.22212013, 0.21708041],
        [0.20622526, 0.22023339, 0.20745694],
        [0.2112533 , 0.21875994, 0.21285112]]))

In [202]:
d_output = np.multiply(np.multiply(E ,slope_output_layer), lr)

In [203]:
d_output

array([[ 0.02130334],
       [ 0.0189425 ],
       [-0.18505613]])

In [204]:
Error_at_hidden_layer = np.dot(d_output, wout.transpose())

In [205]:
Error_at_hidden_layer

array([[ 0.00955631,  0.00966373,  0.01968559],
       [ 0.00849728,  0.00859279,  0.01750402],
       [-0.08301298, -0.08394611, -0.17100316]])

In [206]:
d_hiddenlayer = np.multiply(Error_at_hidden_layer , slope_hidden_layer)

In [207]:
d_hiddenlayer

array([[ 0.00198103,  0.00214651,  0.00427336],
       [ 0.00175235,  0.00189242,  0.00363133],
       [-0.01753677, -0.01836405, -0.03639821]])

In [208]:
wout = wout + np.dot(hiddenlayer_activations.transpose(), d_output) * learning_rate

In [209]:
wout

array([[0.4367422 ],
       [0.44279466],
       [0.91229836]])

In [210]:
wh = wh + np.dot(X.transpose(),d_hiddenlayer) * learning_rate

In [211]:
wh

array([[0.81750346, 0.08677672, 0.86352191],
       [0.73826225, 0.878207  , 0.64746113],
       [0.42860102, 0.69670181, 0.28676828],
       [0.1217106 , 0.11972264, 0.80891032]])

In [212]:
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate

In [213]:
bh

array([[0.73735722, 0.03725478, 0.00323919]])

In [214]:
bout = bout + np.sum(d_output, axis=0) * learning_rate

In [215]:
bout

array([[0.73225721]])